# Generated by Django 6.0.2 on 2026-02-19 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buylist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buylist', to='user_app.company'),
        ),
        migrations.AddField(
            model_name='depo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depolar', to='user_app.company'),
        ),
        migrations.AddField(
            model_name='depo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buylist',
            name='depo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buylist', to='app.depo'),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user_app.company'),
        ),
        migrations.AddField(
            model_name='buylist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
        migrations.AddField(
            model_name='moneytype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneytypes', to='user_app.company'),
        ),
        migrations.AddField(
            model_name='buylist',
            name='money_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.moneytype'),
        ),
        migrations.AddField(
            model_name='unit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='user_app.company'),
        ),
        migrations.AddField(
            model_name='buylist',
            name='item_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unit'),
        ),
    ]
